services:
  spark-master:
    container_name: spark-master
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - ./data:/opt/spark/data
    networks:
      - spark-network     
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master"]

networks:
  spark-network:
    driver: bridge      
